spring.application.name=dryforest
spring.flyway.enabled=false
server.port=8082

# spring.datasource.url=jdbc:postgresql://dpg-d8gm4etckfvc73cs6q8g-a.frankfurt-postgres.render.com:5432/dryforest?ssl=true&sslmode=require
spring.datasource.url=jdbc:postgresql://localhost:5432/dryforest

# spring.datasource.username=voahary
spring.datasource.username=postgres
# spring.datasource.password=y4lTdfLMrP3X9Hs6qtsHZYScOwq03LdC
spring.datasource.password=florentino

spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
spring.jpa.show-sql=true

# spring.datasource.hikari.data-source-properties: ssl=true
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.separator=@@
spring.jpa.defer-datasource-initialization=true
spring.sql.init.schema-locations=classpath:donne_postgresql.sql,classpath:views.sql

jwt.secret=+31flreDydoQAELprT1653k0PR/cp3ZT2DL0FpCQDuHrHBby1GIDLivRsjp7eM4kLe64U7+BBnaTM+GS886lGQ==
jwt.expiration.ms=86400000

sync.pullable-tables-patrol=patrol_group,incident_patrol_type,observation_patrol_type,category_animal,animal
sync.pullable-tables-reforestation=role,person,species_type,species,severity,type_zone,patrol_group,category_animal,animal
